name = "star-wars-trivia"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 SQL Database binding
[[d1_databases]]
binding = "DB"
database_name = "sw-trivia-players"
database_id = "7ec5235f-52ca-42ce-a67f-4edb07db5264"

# Optional: set your admin panel password as an env var
[vars]
ADMIN_SECRET = "933672328"

[build]
command = "npm install"